### ISSUE TITLE
Cleaner theme() arguments to theme_clean_light and theme_clean_dark

### ISSUE THREAD

**Issue by hubcad25** [clessn/clessnverse#43]
Add these lines of code (and remove former arguments) to the `theme()` function of the clessnverse themes.
```
theme(strip.background = element_blank(),
           axis.line = element_blank(),
           axis.ticks = element_blank())
```

**Comment by judith-bourque** [comment]
Error message from `get_hub2_table()` should have been fixed with the last [push to main](https://github.com/clessn/clessnverse/pull/40/commits/881cf5897a411e3df983ed7d4ca5d82a8ede0a87)

@hubcad25 are you working on a branch?

**Comment by judith-bourque** [comment]
@hubcad25 Nice! You can delete the branch if you want :)
