### ISSUE TITLE
Put continuous variable between 0 and 1

### ISSUE THREAD

**Issue by judith-bourque** [clessn/clessnverse#52]
Code and explanation from William Poirier:

`Probablement plus facile de créer une fonction pour faire l’opération que tu veux faire. La fonction scale() est faite pour soustraire la moyenne de la colonne à toute les observations, et a en diviser l’écart-type`

```
scaling_01 <- function(vector){
  min <- min(vector)
  max <- max(vector)
  output <- (vector-min)/(max-min)
  return(output)
}
sapply(data,scaling_01)
```

See documentation and tests in https://github.com/clessn/editwars/tree/11-standardise-edit-war-reverts-and-fatalities-variables

**Comment by hubcad25** [comment]
I suggest this:

```
minmaxNormalization <- function(x) {
  return((x-min(x, na.rm = T))/(max(x, na.rm = T)-min(x, na.rm = T)))
}
```

It does not require using sapply after. You can simply do this for example:

```
Data$normalized_variable <- minmaxNormalization(Data$variable)
```

However, we should do the necessary research as to know what is the relevant term here. I'm not quite sure it is "normalization"

**Comment by judith-bourque** [comment]
```
minmaxNormalization <- function(x) {
  min <- min(x, na.rm = T)
  max <- max(x, na.rm = T)
  output <- (x - min )/(max - min)
  return(output)
}
```
