### ISSUE TITLE
Check if element missing from vector

### ISSUE THREAD

**Issue by judith-bourque** [clessn/clessnverse#74]
# Function
Based on `purrr::has_element()`
```R
misses_element <- function(.x, .y) {
    purrr::none(.x, identical, .y)
}
```
# Examples
```R
# Hubert's example
x <- c(3, 5, 7, 2, 4)

x |> misses_element(5)
# [1] FALSE

x |> misses_element(6)
# [1] TRUE

# Purrr::has_element examples
x <- list(1:10, 5, 9.9)

x |> misses_element(1:10)
# [1] FALSE

x |> misses_element(3)
# [1] TRUE
```

**Comment by judith-bourque** [comment]
@hubcad25 See above for a proposed alternative to `!(5 %in% c(3,5,7,2,4))`

**Comment by hubcad25** [comment]
For example, I am often using `%in%` in dplyr code like this:

`data %>% filter(variable %in% c(2,5,6))`

**Comment by judith-bourque** [comment]
You could probably do
'''
data %>%
   filter(accross(variable, ~ misses_element(.x, 5))
'''

**Comment by judith-bourque** [comment]
It's a question of style, so there's no right answer. `misses_element()` is closer to the tidyverse style, while `%nin%` is closer to base R.

Since most of clessn writes in base R, `%nin%` might be more useful for the team.

Could also name it `%notin%`.

**Comment by judith-bourque** [comment]
Another option could be creating those two functions and putting them in one .rd file. 

Specify which one is compatible with tidyverse and base R.

**Comment by judith-bourque** [comment]
`%notin%` [examples](https://sparkbyexamples.com/r-programming/notin-operator-in-r/)

**Comment by judith-bourque** [comment]
Closing as package no longer actively being developped as of #135.
